name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Vscode release plugin
        uses: JCofman/vscodeaction@1.0.0
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
