name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Master
        uses: actions/bin/filter@master
        with:
          args: branch master

      - name: Yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Publish
        uses: lannonbr/vsce-action@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
